name: Reco Morning (08:00 KST)

on:
  schedule:
    - cron: "0 23 * * *"     # 매일 23:00 UTC = 08:00 KST
  workflow_dispatch:         # 수동 실행용 (테스트할 때 버튼으로 실행 가능)

jobs:
  call-reco-morning:
    runs-on: ubuntu-latest
    steps:
      - name: Call /cron/send-reco?time=아침
        run: |
          curl -s "https://nyamnyam2-back.onrender.com/cron/send-reco?time=아침"
