name: Reco Late (21:00 KST)

on:
  schedule:
    - cron: "0 12 * * *"     # 12:00 UTC = 21:00 KST
  workflow_dispatch:

jobs:
  call-reco-late:
    runs-on: ubuntu-latest
    steps:
      - name: Call /cron/send-reco?time=야식
        run: |
          curl -s "https://nyamnyam2-back.onrender.com/cron/send-reco?time=야식"
